# ---------------------------------------------------------------------------
# Command: /dev:dot-file
#
# Description:
#   Creates a .dot file representing the project based on spec.md and other files.
#   Based on create-dot-file.md functionality.
#
# Usage Example:
#   /dev:dot-file
# ---------------------------------------------------------------------------

name = "dev:dot-file"
description = "Creates a .dot file representing the project structure"

prompt = """
Take a look at spec.md, prompt_plan.md, and any other relevant files. Combine them together to create a .dot file that represents this project. Use ultrathink. Do a really good job. the team is counting on you.

After you are done creating the .dot file, please make sure that it generates a valid graph. You can use the following command to validate the .dot file:

```
dot -Tpng input.dot -o output.png
```
"""