# ---------------------------------------------------------------------------
# Command: /issues:handle
#
# Description:
#   Handles a GitHub issue with a detailed plan, implementation, and PR workflow.
#   Combines functionality from do-issues.md and gh-issue.md
#
# Usage Example:
#   /issues:handle 123
# ---------------------------------------------------------------------------

name = "issues:handle"
description = "Handles a GitHub issue with plan, implementation and PR"

prompt = """
1. Open GitHub issue #{{args}}.
2. Post a detailed plan in a comment on the issue.
3. Create a new branch and implement your plan:
   - Write robust, well-documented code.
   - Include comprehensive tests and debug logging.
   - Confirm that all tests pass.
4. Commit your changes and open a pull request referencing the issue.
5. Keep the issue open until the pull request is merged.
"""