# ---------------------------------------------------------------------------
# Command: /project:initiate
#
# Description:
#   Initiates an iterative process to develop a detailed specification for an
#   idea. The AI will ask one question at a time, building on previous
#   answers to create a thorough spec.
#
# Usage Example:
#   /project:initiate A mobile app that tracks personal reading habits
# ---------------------------------------------------------------------------

name = "project:initiate"
description = "Asks questions iteratively to develop a thorough, step-by-step specification for an idea"

prompt = """
Ask me one question at a time so we can develop a thorough, step-by-step spec for this idea.
Our goal is to have a detailed specification.

Let's structure our conversation around these key areas, in order:

1.  **Functional Requirements:** What should the project do?
2.  **Non-Functional Requirements:** What are the constraints (performance, security, etc.)?
3.  **Architecture:** What tech stack and design patterns are preferred?
4.  **Data Handling:** How should data be stored, processed, and output?
5.  **Error Handling:** How should the system behave on failure?
6.  **Testing Plan:** How will we ensure the project is working correctly?

Start by asking me a question about the **Functional Requirements**. Remember, only one question at a time.

Here's the idea:

```
{{args}}
```
"""
