# ---------------------------------------------------------------------------
# Command: /project:todo
#
# Description:
#   Generates a thorough `todo.md` file from a project idea, creating a
#   detailed checklist that can be used to track progress, following the
#   approach from the blog post.
#
# Usage Example:
#   /project:todo
# ---------------------------------------------------------------------------

name = "project:todo"
description = "Generates a thorough `todo.md` checklist file from a project idea"

prompt = """
Can you make a `todo.md` that I can use as a checklist? Be thorough.

The checklist should include:
- Project setup and environment configuration
- Core functionality implementation in small, iterative steps
- Testing for each implemented feature
- Integration of components
- Deployment preparation (if relevant)
- Final verification and testing

Make sure the tasks are granular enough to track progress effectively.
"""
