# ---------------------------------------------------------------------------
# Command: /plan:ask-me
#
# Description:
#   Initiates an iterative process to develop a detailed specification for an
#   idea. The AI will ask one question at a time, building on previous
#   answers to create a thorough spec.
#
# Usage Example:
#   /plan:ask-me mobile app that tracks personal reading habits
# ---------------------------------------------------------------------------

name = "plan:ask-me"
description = "Asks question to develop a thorough, step-by-step spec for an idea."

prompt = """
Ask me one question at a time so we can develop a thorough, step-by-step spec for this idea.
Each question should build on my previous answers, and our end goal is to have a detailed specification I can hand off to a developer.
Let’s do this iteratively and dig into every relevant detail. Remember, only one question at a time.

Here’s the idea:

```
{{args}}
```
"""
