# ---------------------------------------------------------------------------
# Command: /plan:run
#
# Description:
#   Executes prompts from a generated prompt file (prompt.md or ttd-prompt.md)
#   in an automated sequence. For TDD workflow, it will run tests after each
#   implementation step to verify functionality.
#
# Usage Example:
#   /plan:run ttd-prompt.md
# ---------------------------------------------------------------------------

name = "plan:run"
description = "Executes prompts from a generated prompt file in an automated sequence with optional automated testing"

prompt = """
I'll help you run through the prompts in the generated prompt file to implement your project step by step.

For TDD workflow (ttd-prompt.md), I will:
1. Execute each prompt (e.g., create test files)
2. Automatically run tests to see the expected failures
3. Execute implementation prompts (e.g., create implementation files to pass tests)
4. Run tests again to verify they pass
5. Continue to the next test/implementation pair

For regular workflow (prompt.md), I will:
1. Execute each prompt in sequence
2. Verify implementation steps are completed before moving forward

Please specify which prompt file you'd like to run:

```
{{args}}
```

Based on the file type, I'll follow the appropriate automated execution strategy.
"""